// Generated by Xata Codegen 0.26.7. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "users",
    columns: [
      { name: "name", type: "string" },
      { name: "email", type: "email", unique: true },
      { name: "github_username", type: "string" },
      { name: "linkedin_handle", type: "string" },
      { name: "bio", type: "text" },
    ],
    revLinks: [
      { column: "owner_id", table: "projects" },
      { column: "contributor", table: "project_contributors" },
      { column: "user", table: "users_skills" },
    ],
  },
  {
    name: "projects",
    columns: [
      { name: "name", type: "string" },
      { name: "website_url", type: "string" },
      { name: "description", type: "text" },
      { name: "status", type: "string" },
      { name: "owner_id", type: "link", link: { table: "users" } },
    ],
    revLinks: [
      { column: "project", table: "project_contributors" },
      { column: "project", table: "projects_skills" },
      { column: "project", table: "project_science_fields" },
    ],
  },
  {
    name: "project_contributors",
    columns: [
      { name: "contributor", type: "link", link: { table: "users" } },
      { name: "project", type: "link", link: { table: "projects" } },
      { name: "status", type: "string" },
      { name: "contributor_rating", type: "int" },
      { name: "contribution_feedback", type: "text" },
    ],
  },
  {
    name: "skills",
    columns: [{ name: "name", type: "string", unique: true }],
    revLinks: [
      { column: "skills", table: "projects_skills" },
      { column: "skill", table: "users_skills" },
    ],
  },
  {
    name: "projects_skills",
    columns: [
      { name: "project", type: "link", link: { table: "projects" } },
      { name: "skills", type: "link", link: { table: "skills" } },
    ],
  },
  {
    name: "science_fields",
    columns: [{ name: "name", type: "string", unique: true }],
    revLinks: [{ column: "science_field", table: "project_science_fields" }],
  },
  {
    name: "users_skills",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "skill", type: "link", link: { table: "skills" } },
    ],
  },
  {
    name: "project_science_fields",
    columns: [
      {
        name: "science_field",
        type: "link",
        link: { table: "science_fields" },
      },
      { name: "project", type: "link", link: { table: "projects" } },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Omar-Junior-s-workspace-i6qn4t.us-east-1.xata.sh/db/nasa-2023-marketplace",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
